version: 2
updates:
  # Atualiza as dependências npm (produção e dev)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly" # pode ser "daily", "weekly" ou "monthly"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    # Agrupa patches e minors em um único PR
    groups:
      safe-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Evita abrir PRs para dependências que você quer manter fixas
    ignore:
      - dependency-name: "typescript"
        versions: ["<5.0.0"]
      - dependency-name: "@types/node"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Atualiza as GitHub Actions (workflow CI/CD)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(ci)"
