name: Dependency Update

on:
  schedule:
    - cron: '0 0 * * 1' # Toda segunda-feira à meia-noite UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  workflows: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Check outdated packages
        run: npm outdated || true

      - name: Update dependencies
        run: |
          npm update
          npm audit fix --force || true

      - name: Run tests
        run: npm test || true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dependency-update
          delete-branch: true
          title: '🔄 Automated Dependency Update'
          commit-message: 'chore: automated dependency update'
